name: AC Video Viewer
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Kafka topic to consume video frames from
    defaultValue: ac-video-frames
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
