"""
Assetto Corsa Competizione shared memory struct definitions.

Source: ACC Shared Memory Documentation v1.8.12 (Kunos, 2020).
PDF: docs/ACCSharedMemoryDocumentationV1.8.12.pdf

ACC reuses AC's three shared-memory regions (acpmf_physics, acpmf_graphics,
acpmf_static) but extends each struct with additional fields appended at the
end. Common fields keep the same offsets so AC-targeted readers see partial
data without crashing.

Field order is CRITICAL — ctypes reads sequentially from the memory-mapped
region. _pack_ = 4 matches the AC convention and Kunos' compiler defaults.

`c_wchar` on Windows is 2-byte UTF-16, matching Kunos' `wchar_t`. On macOS/Linux
it is 4-byte; do not rely on string fields when running off Windows.
"""

import ctypes


class ACCPhysics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        # --- shared with AC (must keep order/types) ---
        ("packetId", ctypes.c_int32),
        ("gas", ctypes.c_float),
        ("brake", ctypes.c_float),
        ("fuel", ctypes.c_float),
        ("gear", ctypes.c_int32),
        ("rpms", ctypes.c_int32),
        ("steerAngle", ctypes.c_float),
        ("speedKmh", ctypes.c_float),
        ("velocity", ctypes.c_float * 3),
        ("accG", ctypes.c_float * 3),
        ("wheelSlip", ctypes.c_float * 4),
        ("wheelLoad", ctypes.c_float * 4),
        ("wheelsPressure", ctypes.c_float * 4),
        ("wheelAngularSpeed", ctypes.c_float * 4),
        ("tyreWear", ctypes.c_float * 4),
        ("tyreDirtyLevel", ctypes.c_float * 4),
        ("tyreCoreTemperature", ctypes.c_float * 4),
        ("camberRAD", ctypes.c_float * 4),
        ("suspensionTravel", ctypes.c_float * 4),
        ("drs", ctypes.c_float),
        ("tc", ctypes.c_float),
        ("heading", ctypes.c_float),
        ("pitch", ctypes.c_float),
        ("roll", ctypes.c_float),
        ("cgHeight", ctypes.c_float),
        ("carDamage", ctypes.c_float * 5),
        ("numberOfTyresOut", ctypes.c_int32),
        ("pitLimiterOn", ctypes.c_int32),
        ("abs", ctypes.c_float),
        ("kersCharge", ctypes.c_float),
        ("kersInput", ctypes.c_float),
        ("autoShifterOn", ctypes.c_int32),
        ("rideHeight", ctypes.c_float * 2),
        ("turboBoost", ctypes.c_float),
        ("ballast", ctypes.c_float),
        ("airDensity", ctypes.c_float),
        ("airTemp", ctypes.c_float),
        ("roadTemp", ctypes.c_float),
        ("localAngularVel", ctypes.c_float * 3),
        ("finalFF", ctypes.c_float),
        ("performanceMeter", ctypes.c_float),
        ("engineBrake", ctypes.c_int32),
        ("ersRecoveryLevel", ctypes.c_int32),
        ("ersPowerLevel", ctypes.c_int32),
        ("ersHeatCharging", ctypes.c_int32),
        ("ersIsCharging", ctypes.c_int32),
        ("kersCurrentKJ", ctypes.c_float),
        ("drsAvailable", ctypes.c_int32),
        ("drsEnabled", ctypes.c_int32),
        ("brakeTemp", ctypes.c_float * 4),
        ("clutch", ctypes.c_float),
        ("tyreTempI", ctypes.c_float * 4),
        ("tyreTempM", ctypes.c_float * 4),
        ("tyreTempO", ctypes.c_float * 4),
        ("isAIControlled", ctypes.c_int32),
        ("tyreContactPoint", (ctypes.c_float * 3) * 4),
        ("tyreContactNormal", (ctypes.c_float * 3) * 4),
        ("tyreContactHeading", (ctypes.c_float * 3) * 4),
        ("brakeBias", ctypes.c_float),
        ("localVelocity", ctypes.c_float * 3),
        # --- ACC-only additions ---
        ("P2PActivation", ctypes.c_int32),
        ("P2PStatus", ctypes.c_int32),
        ("currentMaxRpm", ctypes.c_float),
        ("mz", ctypes.c_float * 4),
        ("fx", ctypes.c_float * 4),
        ("fy", ctypes.c_float * 4),
        ("slipRatio", ctypes.c_float * 4),
        ("slipAngle", ctypes.c_float * 4),
        ("tcinAction", ctypes.c_int32),
        ("absInAction", ctypes.c_int32),
        ("suspensionDamage", ctypes.c_float * 4),
        ("tyreTemp", ctypes.c_float * 4),
        ("waterTemp", ctypes.c_float),
        ("brakePressure", ctypes.c_float * 4),
        ("frontBrakeCompound", ctypes.c_int32),
        ("rearBrakeCompound", ctypes.c_int32),
        ("padLife", ctypes.c_float * 4),
        ("discLife", ctypes.c_float * 4),
        ("ignitionOn", ctypes.c_int32),
        ("starterEngineOn", ctypes.c_int32),
        ("isEngineRunning", ctypes.c_int32),
        ("kerbVibration", ctypes.c_float),
        ("slipVibrations", ctypes.c_float),
        ("gVibrations", ctypes.c_float),
        ("absVibrations", ctypes.c_float),
    ]


class ACCGraphics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ("packetId", ctypes.c_int32),
        ("status", ctypes.c_int32),
        ("session", ctypes.c_int32),
        ("currentTime", ctypes.c_wchar * 15),
        ("lastTime", ctypes.c_wchar * 15),
        ("bestTime", ctypes.c_wchar * 15),
        ("split", ctypes.c_wchar * 15),
        ("completedLaps", ctypes.c_int32),
        ("position", ctypes.c_int32),
        ("iCurrentTime", ctypes.c_int32),
        ("iLastTime", ctypes.c_int32),
        ("iBestTime", ctypes.c_int32),
        ("sessionTimeLeft", ctypes.c_float),
        ("distanceTraveled", ctypes.c_float),
        ("isInPit", ctypes.c_int32),
        ("currentSectorIndex", ctypes.c_int32),
        ("lastSectorTime", ctypes.c_int32),
        ("numberOfLaps", ctypes.c_int32),
        ("tyreCompound", ctypes.c_wchar * 33),
        ("replayTimeMultiplier", ctypes.c_float),
        ("normalizedCarPosition", ctypes.c_float),
        # --- ACC-specific from here ---
        ("activeCars", ctypes.c_int32),
        ("carCoordinates", (ctypes.c_float * 3) * 60),
        ("carID", ctypes.c_int32 * 60),
        ("playerCarID", ctypes.c_int32),
        ("penaltyTime", ctypes.c_float),
        ("flag", ctypes.c_int32),
        ("penalty", ctypes.c_int32),
        ("idealLineOn", ctypes.c_int32),
        ("isInPitLane", ctypes.c_int32),
        ("surfaceGrip", ctypes.c_float),
        ("mandatoryPitDone", ctypes.c_int32),
        ("windSpeed", ctypes.c_float),
        ("windDirection", ctypes.c_float),
        ("isSetupMenuVisible", ctypes.c_int32),
        ("mainDisplayIndex", ctypes.c_int32),
        ("secondaryDisplyIndex", ctypes.c_int32),
        ("TC", ctypes.c_int32),
        ("TCCUT", ctypes.c_int32),
        ("EngineMap", ctypes.c_int32),
        ("ABS", ctypes.c_int32),
        ("fuelXLap", ctypes.c_float),
        ("rainLights", ctypes.c_int32),
        ("flashingLights", ctypes.c_int32),
        ("lightsStage", ctypes.c_int32),
        ("exhaustTemperature", ctypes.c_float),
        ("wiperLV", ctypes.c_int32),
        ("driverStintTotalTimeLeft", ctypes.c_int32),
        ("driverStintTimeLeft", ctypes.c_int32),
        ("rainTyres", ctypes.c_int32),
        ("sessionIndex", ctypes.c_int32),
        ("usedFuel", ctypes.c_float),
        ("deltaLapTime", ctypes.c_wchar * 15),
        ("iDeltaLapTime", ctypes.c_int32),
        ("estimatedLapTime", ctypes.c_wchar * 15),
        ("iEstimatedLapTime", ctypes.c_int32),
        ("isDeltaPositive", ctypes.c_int32),
        ("iSplit", ctypes.c_int32),
        ("isValidLap", ctypes.c_int32),
        ("fuelEstimatedLaps", ctypes.c_float),
        ("trackStatus", ctypes.c_wchar * 33),
        ("missingMandatoryPits", ctypes.c_int32),
        ("Clock", ctypes.c_float),
        ("directionLightsLeft", ctypes.c_int32),
        ("directionLightsRight", ctypes.c_int32),
        ("GlobalYellow", ctypes.c_int32),
        ("GlobalYellow1", ctypes.c_int32),
        ("GlobalYellow2", ctypes.c_int32),
        ("GlobalYellow3", ctypes.c_int32),
        ("GlobalWhite", ctypes.c_int32),
        ("GlobalGreen", ctypes.c_int32),
        ("GlobalChequered", ctypes.c_int32),
        ("GlobalRed", ctypes.c_int32),
        ("mfdTyreSet", ctypes.c_int32),
        ("mfdFuelToAdd", ctypes.c_float),
        ("mfdTyrePressureLF", ctypes.c_float),
        ("mfdTyrePressureRF", ctypes.c_float),
        ("mfdTyrePressureLR", ctypes.c_float),
        ("mfdTyrePressureRR", ctypes.c_float),
        ("trackGripStatus", ctypes.c_int32),
        ("rainIntensity", ctypes.c_int32),
        ("rainIntensityIn10min", ctypes.c_int32),
        ("rainIntensityIn30min", ctypes.c_int32),
        ("currentTyreSet", ctypes.c_int32),
        ("strategyTyreSet", ctypes.c_int32),
        ("gapAhead", ctypes.c_int32),
        ("gapBehind", ctypes.c_int32),
    ]


class ACCStatic(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ("smVersion", ctypes.c_wchar * 15),
        ("acVersion", ctypes.c_wchar * 15),
        ("numberOfSessions", ctypes.c_int32),
        ("numCars", ctypes.c_int32),
        ("carModel", ctypes.c_wchar * 33),
        ("track", ctypes.c_wchar * 33),
        ("playerName", ctypes.c_wchar * 33),
        ("playerSurname", ctypes.c_wchar * 33),
        ("playerNick", ctypes.c_wchar * 33),
        ("sectorCount", ctypes.c_int32),
        ("maxTorque", ctypes.c_float),
        ("maxPower", ctypes.c_float),
        ("maxRpm", ctypes.c_int32),
        ("maxFuel", ctypes.c_float),
        ("suspensionMaxTravel", ctypes.c_float * 4),
        ("tyreRadius", ctypes.c_float * 4),
        ("maxTurboBoost", ctypes.c_float),
        ("deprecated_1", ctypes.c_float),
        ("deprecated_2", ctypes.c_float),
        ("penaltiesEnabled", ctypes.c_int32),
        ("aidFuelRate", ctypes.c_float),
        ("aidTireRate", ctypes.c_float),
        ("aidMechanicalDamage", ctypes.c_float),
        ("allowTyreBlankets", ctypes.c_int32),
        ("aidStability", ctypes.c_float),
        ("aidAutoClutch", ctypes.c_int32),
        ("aidAutoBlip", ctypes.c_int32),
        ("hasDRS", ctypes.c_int32),
        ("hasERS", ctypes.c_int32),
        ("hasKERS", ctypes.c_int32),
        ("kersMaxJoules", ctypes.c_float),
        ("engineBrakeSettingsCount", ctypes.c_int32),
        ("ersPowerControllerCount", ctypes.c_int32),
        ("trackSplineLength", ctypes.c_float),
        ("trackConfiguration", ctypes.c_wchar * 15),
        ("ersMaxJ", ctypes.c_float),
        ("isTimedRace", ctypes.c_int32),
        ("hasExtraLap", ctypes.c_int32),
        ("carSkin", ctypes.c_wchar * 33),
        ("reversedGridPositions", ctypes.c_int32),
        ("pitWindowStart", ctypes.c_int32),
        ("pitWindowEnd", ctypes.c_int32),
        # --- ACC-only additions ---
        ("isOnline", ctypes.c_int32),
        ("dryTyresName", ctypes.c_wchar * 33),
        ("wetTyresName", ctypes.c_wchar * 33),
    ]
