# Stage 1: Build
FROM node:20-bookworm-slim AS builder
WORKDIR /app

ARG API_URL=http://leaderboard-service
ENV API_URL=$API_URL

ARG NEXT_PUBLIC_LEADERBOARD_SERVICE_URL=https://leaderboard-service-9cb716a-demo-acquixbridge-dev.edge.byox.demo
ENV NEXT_PUBLIC_LEADERBOARD_SERVICE_URL=$NEXT_PUBLIC_LEADERBOARD_SERVICE_URL

ARG NEXT_PUBLIC_FREEZE_MS
ENV NEXT_PUBLIC_FREEZE_MS=$NEXT_PUBLIC_FREEZE_MS

COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:20-bookworm-slim
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --omit=dev
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
CMD ["npm", "start"]
