name: Telemetry Enrichment
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Raw telemetry topic to enrich
    defaultValue: ac-telemetry-raw
    required: true
  - name: output
    inputType: OutputTopic
    description: Enriched telemetry output topic
    defaultValue: ac-telemetry-enriched
    required: true
  - name: config_topic
    inputType: InputTopic
    description: Dynamic Configuration Manager topic
    defaultValue: ac-telemetry-config
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
