FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
COPY static/ static/
EXPOSE 80
ENTRYPOINT ["uvicorn", "main:api", "--host", "0.0.0.0", "--port", "80"]
