name: backend
language: python
variables:
  - name: MONGO_USER
    inputType: Secret
    multiline: false
    defaultValue: MONGO_USER
    required: true
  - name: MONGO_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: MONGO_PASSWORD
    required: true
  - name: MONGO_HOST
    inputType: FreeText
    multiline: false
    defaultValue: mongodb
    required: true
  - name: CONFIG_API_URL
    inputType: FreeText
    multiline: false
    required: true
  - name: QUIXLAKE_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://quixlake-quixdev-quixlakev2-dev.deployments-dev.quix.io
    required: true
  - name: QUIX_LAKE_TOKEN
    inputType: Secret
    multiline: false
    defaultValue: pat_token
    required: true
  - name: LOCAL_DEV_MODE
    inputType: FreeText
    multiline: false
    defaultValue: false
  - name: LIVE_TELEMETRY_ENABLED
    inputType: FreeText
    multiline: false
    defaultValue: true
  - name: Quix__Portal__Api
    inputType: FreeText
    multiline: false
    defaultValue: https://portal-api.dev.quix.io
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
